CREATE TABLE "user_pools" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"pool_name" varchar(100) DEFAULT 'My Pool' NOT NULL,
	"pool_length" numeric(5, 2) NOT NULL,
	"pool_width" numeric(5, 2) NOT NULL,
	"pool_depth_shallow" numeric(4, 2) NOT NULL,
	"pool_depth_deep" numeric(4, 2) NOT NULL,
	"pool_shape" varchar(20) NOT NULL,
	"pool_type" varchar(20) NOT NULL,
	"pool_volume" integer NOT NULL,
	"pump_type" varchar(30) NOT NULL,
	"pump_horsepower" numeric(3, 2) NOT NULL,
	"pump_age_years" integer NOT NULL,
	"pump_flow_rate" numeric(6, 2),
	"variable_speed_low_rpm" integer,
	"variable_speed_medium_rpm" integer,
	"variable_speed_high_rpm" integer,
	"zip_code" varchar(10) NOT NULL,
	"state" varchar(2) NOT NULL,
	"city" varchar(100),
	"climate_zone" varchar(30) NOT NULL,
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"usage_level" varchar(20) NOT NULL,
	"average_swimmers" integer NOT NULL,
	"landscaping" varchar(20) NOT NULL,
	"screen_enclosure" boolean DEFAULT false NOT NULL,
	"has_waterfall" boolean DEFAULT false NOT NULL,
	"has_heater" boolean DEFAULT false NOT NULL,
	"has_salt_system" boolean DEFAULT false NOT NULL,
	"water_clarity" varchar(30) NOT NULL,
	"electricity_rate" numeric(5, 3) NOT NULL,
	"has_time_of_use_pricing" boolean DEFAULT false,
	"tou_peak_rate" numeric(5, 3),
	"tou_off_peak_rate" numeric(5, 3),
	"tou_peak_hours_start" integer,
	"tou_peak_hours_end" integer,
	"current_daily_runtime" numeric(4, 2) NOT NULL,
	"required_turnovers" numeric(3, 2),
	"recommended_runtime" numeric(4, 2),
	"daily_cost" numeric(8, 2),
	"monthly_cost" numeric(8, 2),
	"annual_cost" numeric(8, 2),
	"current_daily_cost" numeric(8, 2),
	"current_monthly_cost" numeric(8, 2),
	"current_annual_cost" numeric(8, 2),
	"daily_savings" numeric(8, 2),
	"monthly_savings" numeric(8, 2),
	"annual_savings" numeric(8, 2),
	"percent_reduction" numeric(5, 2),
	"daily_kwh" numeric(8, 2),
	"monthly_kwh" numeric(8, 2),
	"annual_kwh" numeric(8, 2),
	"schedule_blocks" varchar(2000),
	"is_primary" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"full_name" varchar(255),
	"phone" varchar(20),
	"default_location" varchar(100),
	"default_electricity_rate" numeric(5, 3) DEFAULT '0.14' NOT NULL,
	"default_pump_type" varchar(50),
	"measurement_units" varchar(10) DEFAULT 'gallons' NOT NULL,
	"auto_calculate" boolean DEFAULT false NOT NULL,
	"email_notifications" boolean DEFAULT true NOT NULL,
	"maintenance_reminders" boolean DEFAULT true NOT NULL,
	"weekly_reports" boolean DEFAULT false NOT NULL,
	"seasonal_alerts" boolean DEFAULT true NOT NULL,
	"savings_milestones" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_settings_user_id_unique" UNIQUE("user_id")
);
