import type { CalculationResult, EnergyCostData } from '@/types/calculator';
import JsPDF from 'jspdf';

export const exportCalculatorResultsPDF = (
  results: CalculationResult,
  currentRuntime: number,
  _energyData: EnergyCostData,
) => {
  const doc = new JsPDF();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.text('PoolPumpCalc', 20, 20);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Pool Pump Optimization Results', 20, 35);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 42);

  // Optimal Runtime Section
  let yPos = 55;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Optimal Runtime', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);
  doc.setTextColor(16, 185, 129);
  doc.text(`Recommended Runtime: ${results.optimalRuntime.toFixed(1)} hours/day`, 20, yPos);

  yPos += 6;
  doc.setTextColor(0, 0, 0);
  doc.text(`Current Runtime: ${currentRuntime} hours/day`, 20, yPos);

  yPos += 6;
  doc.setTextColor(16, 185, 129);
  doc.text(`Reduction: ${results.costs.savings.percentReduction.toFixed(1)}%`, 20, yPos);

  // Cost Savings Breakdown
  yPos += 15;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Cost Savings Breakdown', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);
  doc.setTextColor(220, 38, 38);
  doc.text(`Current Monthly Cost: $${results.costs.currentCosts.monthlyCost.toFixed(2)}`, 20, yPos);

  yPos += 6;
  doc.setTextColor(16, 185, 129);
  doc.text(`Optimized Monthly Cost: $${results.costs.optimizedCosts.monthlyCost.toFixed(2)}`, 20, yPos);

  yPos += 10;
  doc.setTextColor(0, 0, 0);
  doc.text('Savings:', 20, yPos);

  yPos += 6;
  doc.setTextColor(16, 185, 129);
  doc.text(`  Monthly: $${results.costs.savings.monthlySavings.toFixed(2)}`, 20, yPos);
  yPos += 6;
  doc.text(`  Annual: $${results.costs.savings.annualSavings.toFixed(2)}`, 20, yPos);
  yPos += 6;
  doc.text(`  5-Year: $${(results.costs.savings.annualSavings * 5).toFixed(2)}`, 20, yPos);

  yPos += 10;
  doc.setTextColor(37, 99, 235);
  doc.text(`Energy Saved: ${results.costs.savings.annualKwhSaved.toFixed(0)} kWh/year`, 20, yPos);

  yPos += 6;
  doc.setTextColor(100, 100, 100);
  const co2Reduction = (results.costs.savings.annualKwhSaved * 0.92).toFixed(0);
  doc.text(`Environmental Impact: ~${co2Reduction} lbs CO2 reduction/year`, 20, yPos);

  // Recommended Schedule
  yPos += 15;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Recommended Schedule', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);

  if (results.schedule.length > 0) {
    results.schedule.forEach((block, index) => {
      const formatTime = (hour: number) => {
        const period = hour >= 12 ? 'PM' : 'AM';
        const displayHour = hour === 0 ? 12 : hour > 12 ? hour - 12 : hour;
        return `${displayHour}:00 ${period}`;
      };

      const speedLabel = block.speedSetting ? ` (${block.speedSetting} speed)` : '';
      doc.text(
        `Block ${index + 1}: ${formatTime(block.startHour)} - ${formatTime(block.endHour)}${speedLabel}`,
        25,
        yPos,
      );
      yPos += 6;
    });
  } else {
    doc.text('No schedule blocks available', 25, yPos);
    yPos += 6;
  }

  // Personalized Recommendations
  if (results.recommendations.length > 0) {
    yPos += 10;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Personalized Recommendations', 20, yPos);

    yPos += 10;
    doc.setFontSize(10);

    results.recommendations.forEach((rec, index) => {
      // Check if we need a new page
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      doc.setTextColor(37, 99, 235);
      doc.text(`${index + 1}.`, 20, yPos);
      doc.setTextColor(0, 0, 0);

      // Split long recommendations into multiple lines
      const maxWidth = 170;
      const lines = doc.splitTextToSize(rec, maxWidth);
      doc.text(lines, 28, yPos);
      yPos += (lines.length * 6);
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by PoolPumpCalc - Visit poolpumpcalc.com for more information', 20, 280);

  // Save the PDF
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`Pool_Optimization_Results_${timestamp}.pdf`);
};
