import type { UserPool } from '@/models/Schema';
import type { ScheduleBlock } from '@/types/calculator';
import JsPDF from 'jspdf';

export function exportSchedulePDF(pool: UserPool) {
  const doc = new JsPDF();

  // Parse schedule blocks
  let scheduleBlocks: ScheduleBlock[] = [];
  if (pool.scheduleBlocks) {
    try {
      scheduleBlocks = JSON.parse(pool.scheduleBlocks);
    } catch {
      scheduleBlocks = [];
    }
  }

  // Header
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.text('PoolCalc', 20, 20);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Pool Optimization Schedule: ${pool.poolName}`, 20, 35);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 42);

  // Pool Details
  let yPos = 55;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Pool Details', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);
  doc.text(`Volume: ${Number(pool.poolVolume).toLocaleString()} gallons`, 20, yPos);
  yPos += 6;
  doc.text(`Shape: ${pool.poolShape} (${pool.poolType})`, 20, yPos);
  yPos += 6;
  doc.text(`Location: ${pool.city}, ${pool.state} (${pool.climateZone})`, 20, yPos);
  yPos += 6;
  doc.text(`Pump: ${pool.pumpType}, ${Number(pool.pumpHorsepower)} HP`, 20, yPos);

  // Optimization Results
  yPos += 15;
  doc.setFontSize(14);
  doc.text('Optimization Results', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);
  doc.setTextColor(16, 185, 129);
  doc.text(`Recommended Runtime: ${Number(pool.recommendedRuntime || 0).toFixed(1)} hours/day`, 20, yPos);

  yPos += 6;
  doc.setTextColor(0, 0, 0);
  doc.text(`Current Runtime: ${Number(pool.currentDailyRuntime)} hours/day`, 20, yPos);

  yPos += 6;
  doc.setTextColor(16, 185, 129);
  doc.text(`Reduction: ${Number(pool.percentReduction || 0).toFixed(1)}%`, 20, yPos);

  // Cost Savings
  yPos += 15;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Cost Savings', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);
  doc.text(`Monthly Savings: $${Number(pool.monthlySavings || 0).toFixed(2)}`, 20, yPos);
  yPos += 6;
  doc.text(`Annual Savings: $${Number(pool.annualSavings || 0).toFixed(2)}`, 20, yPos);
  yPos += 6;
  doc.text(`5-Year Savings: $${(Number(pool.annualSavings || 0) * 5).toFixed(2)}`, 20, yPos);

  // Schedule
  yPos += 15;
  doc.setFontSize(14);
  doc.text('Recommended Schedule', 20, yPos);

  yPos += 10;
  doc.setFontSize(10);

  if (scheduleBlocks.length > 0) {
    scheduleBlocks.forEach((block, index) => {
      const formatTime = (hour: number) => {
        const period = hour >= 12 ? 'PM' : 'AM';
        const displayHour = hour === 0 ? 12 : hour > 12 ? hour - 12 : hour;
        return `${displayHour}:00 ${period}`;
      };

      const speedLabel = block.speedSetting ? ` (${block.speedSetting} speed)` : '';
      doc.text(
        `Block ${index + 1}: ${formatTime(block.startHour)} - ${formatTime(block.endHour)}${speedLabel}`,
        25,
        yPos,
      );
      yPos += 6;
    });
  } else {
    doc.text('No schedule blocks available', 25, yPos);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by PoolCalc - Visit poolcalc.com for more information', 20, 280);

  // Save the PDF
  doc.save(`${pool.poolName.replace(/\s+/g, '_')}_Schedule.pdf`);
}
